name: Compilar LaTeX

on:
  push:
    paths:
      - "pages/**.tex"
      - "pages/**"
      - ".github/workflows/latex.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Compilar LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Portafolio/pages/InformacionColorimetria.tex

      - name: Commit del PDF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add Portafolio/pages/InformacionColorimetria.pdf

          git diff --cached --quiet || (
            git commit -m "Actualizar PDF automáticamente"
            git push
          )
